version: 2

jobs:
  test:
    working_directory: /go/src/github.com/uw-labs/sync
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: go get -u -t ./...
      - run: go test -v -race -cover ./...

workflows:
  version: 2
  test:
    jobs:
      - test
